namespace ScTools.ScriptAssembly.Targets.RDR3;

public interface IOpcodeTraitsRDR3<TOpcode> : IOpcodeTraits<TOpcode> where TOpcode : struct, Enum
{
    public static abstract TOpcode ENTER { get; }
    public static abstract TOpcode SWITCH { get; }
    public static abstract Dictionary<OpcodeV16, string> DumpOpcodeFormats { get; }
}

public abstract class OpcodeTraitsV16 : IOpcodeTraitsRDR3<OpcodeV16>
{
    public const int NumberOfOpcodes = 146;

    static int IOpcodeTraits<OpcodeV16>.NumberOfOpcodes => NumberOfOpcodes;
    public static OpcodeV16 ENTER => OpcodeV16.ENTER;
    public static OpcodeV16 SWITCH => OpcodeV16.SWITCH;

    public static int ConstantByteSize(OpcodeV16 opcode)
        => (int)opcode < NumberOfOpcodes ? ByteSizeMap[opcode] : 1;

    public static int ByteSize(ReadOnlySpan<byte> bytecode)
    {
        var opcode = (OpcodeV16)bytecode[0];
        var s = opcode switch
        {
            OpcodeV16.ENTER => bytecode[4] + 5,
            OpcodeV16.SWITCH => 6 * bytecode[1] + 2,
            _ => ConstantByteSize(opcode),
        };

        return s;
    }

    public static Span<byte> GetInstructionSpan(Span<byte> code, int address)
    {
        var inst = code[address..];
        var instLength = ByteSize(inst);
        return inst[..instLength]; // trim to instruction length
    }

    public static ReadOnlySpan<byte> GetInstructionSpan(ReadOnlySpan<byte> code, int address)
    {
        var inst = code[address..];
        var instLength = ByteSize(inst);
        return inst[..instLength]; // trim to instruction length
    }

    private static readonly Dictionary<OpcodeV16, byte> ByteSizeMap = new Dictionary<OpcodeV16, byte>
    {
        // First 32 opcodes – all sizes 1
        { OpcodeV16.NOP, 1 },
        { OpcodeV16.IADD, 1 },
        { OpcodeV16.ISUB, 1 },
        { OpcodeV16.IMUL, 1 },
        { OpcodeV16.IDIV, 1 },
        { OpcodeV16.IMOD, 1 },
        { OpcodeV16.INOT, 1 },
        { OpcodeV16.INEG, 1 },
        { OpcodeV16.IEQ, 1 },
        { OpcodeV16.INE, 1 },
        { OpcodeV16.IGT, 1 },
        { OpcodeV16.IGE, 1 },
        { OpcodeV16.ILT, 1 },
        { OpcodeV16.ILE, 1 },
        { OpcodeV16.FADD, 1 },
        { OpcodeV16.FSUB, 1 },
        { OpcodeV16.FMUL, 1 },
        { OpcodeV16.FDIV, 1 },
        { OpcodeV16.FMOD, 1 },
        { OpcodeV16.FNEG, 1 },
        { OpcodeV16.FEQ, 1 },
        { OpcodeV16.FNE, 1 },
        { OpcodeV16.FGT, 1 },
        { OpcodeV16.FGE, 1 },
        { OpcodeV16.FLT, 1 },
        { OpcodeV16.FLE, 1 },
        { OpcodeV16.VADD, 1 },
        { OpcodeV16.VSUB, 1 },
        { OpcodeV16.VMUL, 1 },
        { OpcodeV16.VDIV, 1 },
        { OpcodeV16.VNEG, 1 },
        { OpcodeV16.IAND, 1 },
        { OpcodeV16.IOR, 1 },
        { OpcodeV16.IXOR, 1 },
        { OpcodeV16.I2F, 1 },
        { OpcodeV16.F2I, 1 },
        { OpcodeV16.F2V, 1 },
        { OpcodeV16.PUSH_CONST_U8, 2 },
        { OpcodeV16.PUSH_CONST_U8_U8, 3 },
        { OpcodeV16.PUSH_CONST_U8_U8_U8, 4 },
        { OpcodeV16.PUSH_CONST_U32, 5 },
        { OpcodeV16.PUSH_CONST_F, 5 },
        { OpcodeV16.DUP, 1 },
        { OpcodeV16.DROP, 1 },
        { OpcodeV16.NATIVE, 4 },
        { OpcodeV16.ENTER, 0 },
        { OpcodeV16.LEAVE, 3 },
        { OpcodeV16.LOAD, 1 },
        { OpcodeV16.STORE, 1 },
        { OpcodeV16.STORE_REV, 1 },
        { OpcodeV16.LOAD_N, 1 },
        { OpcodeV16.STORE_N, 1 },
        { OpcodeV16.ARRAY_U8, 2 },
        { OpcodeV16.ARRAY_U8_LOAD, 2 },
        { OpcodeV16.ARRAY_U8_STORE, 2 },
        { OpcodeV16.LOCAL_U8, 2 },
        { OpcodeV16.LOCAL_U8_LOAD, 2 },
        { OpcodeV16.LOCAL_U8_STORE, 2 },
        { OpcodeV16.STATIC_U8, 2 },
        { OpcodeV16.STATIC_U8_LOAD, 2 },
        { OpcodeV16.STATIC_U8_STORE, 2 },
        { OpcodeV16.IADD_U8, 1 },
        { OpcodeV16.IMUL_U8, 2 },
        { OpcodeV16.IOFFSET, 2 },
        { OpcodeV16.IOFFSET_U8, 2 },
        { OpcodeV16.IOFFSET_U8_LOAD, 2 },
        { OpcodeV16.IOFFSET_U8_STORE, 2 },
        { OpcodeV16.PUSH_CONST_S16, 3 },
        { OpcodeV16.IADD_S16, 3 },
        { OpcodeV16.IMUL_S16, 3 },
        { OpcodeV16.IOFFSET_S16, 3 },
        { OpcodeV16.IOFFSET_S16_LOAD, 3 },
        { OpcodeV16.IOFFSET_S16_STORE, 3 },
        { OpcodeV16.ARRAY_U16, 4 },
        { OpcodeV16.ARRAY_U16_LOAD, 4 },
        { OpcodeV16.ARRAY_U16_STORE, 4 },
        { OpcodeV16.LOCAL_U16, 4 },
        { OpcodeV16.LOCAL_U16_LOAD, 4 },
        { OpcodeV16.LOCAL_U16_STORE, 4 },
        { OpcodeV16.STATIC_U16, 4 },
        { OpcodeV16.STATIC_U16_LOAD, 4 },
        { OpcodeV16.STATIC_U16_STORE, 4 },
        { OpcodeV16.GLOBAL_U16, 4 },
        { OpcodeV16.GLOBAL_U16_LOAD, 4 },
        { OpcodeV16.GLOBAL_U16_STORE, 4 },
        { OpcodeV16.J, 3 },
        { OpcodeV16.JZ, 3 },
        { OpcodeV16.IEQ_JZ, 3 },
        { OpcodeV16.INE_JZ, 3 },
        { OpcodeV16.IGT_JZ, 3 },
        { OpcodeV16.IGE_JZ, 3 },
        { OpcodeV16.ILT_JZ, 3 },
        { OpcodeV16.ILE_JZ, 3 },
        { OpcodeV16.CALL, 4 },
        { OpcodeV16.GLOBAL_U24, 4 },
        { OpcodeV16.GLOBAL_U24_LOAD, 4 },
        { OpcodeV16.GLOBAL_U24_STORE, 4 },
        { OpcodeV16.PUSH_CONST_U24, 4 },
        { OpcodeV16.SWITCH, 1 },
        { OpcodeV16.STRING, 1 },
        { OpcodeV16.STRINGHASH, 1 },
        { OpcodeV16.TEXT_LABEL_ASSIGN_STRING, 2 },
        { OpcodeV16.TEXT_LABEL_ASSIGN_INT, 2 },
        { OpcodeV16.TEXT_LABEL_APPEND_STRING, 2 },
        { OpcodeV16.TEXT_LABEL_APPEND_INT, 2 },
        { OpcodeV16.TEXT_LABEL_COPY, 1 },
        { OpcodeV16.CATCH, 1 },
        { OpcodeV16.THROW, 1 },
        { OpcodeV16.CALLINDIRECT, 1 },
        { OpcodeV16.PUSH_CONST_M1, 1 },
        { OpcodeV16.PUSH_CONST_0, 1 },
        { OpcodeV16.PUSH_CONST_1, 1 },
        { OpcodeV16.PUSH_CONST_2, 1 },
        { OpcodeV16.PUSH_CONST_3, 1 },
        { OpcodeV16.PUSH_CONST_4, 1 },
        { OpcodeV16.PUSH_CONST_5, 1 },
        { OpcodeV16.PUSH_CONST_6, 1 },
        { OpcodeV16.PUSH_CONST_7, 1 },
        { OpcodeV16.PUSH_CONST_FM1, 1 },
        { OpcodeV16.PUSH_CONST_F0, 1 },
        { OpcodeV16.PUSH_CONST_F1, 1 },
        { OpcodeV16.PUSH_CONST_F2, 1 },
        { OpcodeV16.PUSH_CONST_F3, 1 },
        { OpcodeV16.PUSH_CONST_F4, 1 },
        { OpcodeV16.PUSH_CONST_F5, 1 },
        { OpcodeV16.PUSH_CONST_F6, 1 },
        { OpcodeV16.PUSH_CONST_F7, 1 },
        { OpcodeV16.LOCAL_LOAD_S, 1 },
        { OpcodeV16.LOCAL_STORE_S, 1 },
        { OpcodeV16.LOCAL_STORE_SR, 1 },
        { OpcodeV16.STATIC_LOAD_S, 1 },
        { OpcodeV16.STATIC_STORE_S, 1 },
        { OpcodeV16.STATIC_STORE_SR, 1 },
        { OpcodeV16.LOAD_N_S, 1 },
        { OpcodeV16.STORE_N_S, 1 },
        { OpcodeV16.STORE_N_SR, 1 },
        { OpcodeV16.GLOBAL_LOAD_S, 1 },
        { OpcodeV16.GLOBAL_STORE_S, 1 },
        { OpcodeV16.GLOBAL_STORE_SR, 1 },
        { OpcodeV16.STATIC_U24, 1 },
        { OpcodeV16.STATIC_U24_LOAD, 1 },
        { OpcodeV16.STATIC_U24_STORE, 1 },
    };

    static Dictionary<OpcodeV16, string> IOpcodeTraitsRDR3<OpcodeV16>.DumpOpcodeFormats { get; } = new Dictionary<OpcodeV16, string>
    {
        { OpcodeV16.NOP, "" }, { OpcodeV16.IADD, "" }, { OpcodeV16.ISUB, "" }, { OpcodeV16.IMUL, "" }, { OpcodeV16.IDIV, "" },
        { OpcodeV16.IMOD, "" }, { OpcodeV16.INOT, "" }, { OpcodeV16.INEG, "" }, { OpcodeV16.IEQ, "" }, { OpcodeV16.INE, "" },
        { OpcodeV16.IGT, "" }, { OpcodeV16.IGE, "" }, { OpcodeV16.ILT, "" }, { OpcodeV16.ILE, "" }, { OpcodeV16.FADD, "" }, 
        { OpcodeV16.FSUB, "" }, { OpcodeV16.FMUL, "" }, { OpcodeV16.FDIV, "" }, { OpcodeV16.FMOD, "" }, { OpcodeV16.FNEG, "" }, 
        { OpcodeV16.FEQ, "" }, { OpcodeV16.FNE, "" }, { OpcodeV16.FGT, "" }, { OpcodeV16.FGE, "" }, { OpcodeV16.FLT, "" }, { OpcodeV16.FLE, "" },
        { OpcodeV16.VADD, "" }, { OpcodeV16.VSUB, "" }, { OpcodeV16.VMUL, "" }, { OpcodeV16.VDIV, "" }, { OpcodeV16.VNEG, "" }, { OpcodeV16.IAND, "" },
        { OpcodeV16.IXOR, "" }, { OpcodeV16.I2F, "" }, { OpcodeV16.F2I, "" }, { OpcodeV16.F2V, "" }, 
        { OpcodeV16.PUSH_CONST_U8, "b" }, 
        { OpcodeV16.PUSH_CONST_U8_U8, "bb" }, 
        { OpcodeV16.PUSH_CONST_U8_U8_U8, "bbb" },
        { OpcodeV16.PUSH_CONST_U32, "d" },
        { OpcodeV16.PUSH_CONST_F, "f" },
        { OpcodeV16.DUP, "" },
        { OpcodeV16.DROP, "" },
        { OpcodeV16.NATIVE, "bbb" },
        { OpcodeV16.ENTER, "bs" },
        { OpcodeV16.LEAVE, "bb" },
        { OpcodeV16.LOAD, "" },
        { OpcodeV16.STORE, "" },
        { OpcodeV16.STORE_REV, "" },
        { OpcodeV16.LOAD_N, "" },
        { OpcodeV16.STORE_N, "" },
        { OpcodeV16.ARRAY_U8, "b" },
        { OpcodeV16.ARRAY_U8_LOAD, "b" },
        { OpcodeV16.ARRAY_U8_STORE, "b" },
        { OpcodeV16.LOCAL_U8, "b" },
        { OpcodeV16.LOCAL_U8_LOAD, "b" },
        { OpcodeV16.LOCAL_U8_STORE, "b" },
        { OpcodeV16.STATIC_U8, "b" },
        { OpcodeV16.STATIC_U8_LOAD, "b" },
        { OpcodeV16.STATIC_U8_STORE, "b" },
        { OpcodeV16.IADD_U8, "b" },
        { OpcodeV16.IMUL_U8, "b" },
        { OpcodeV16.IOFFSET, "" },
        { OpcodeV16.IOFFSET_U8, "b" },
        { OpcodeV16.IOFFSET_U8_LOAD, "b" },
        { OpcodeV16.IOFFSET_U8_STORE, "b" },
        { OpcodeV16.PUSH_CONST_S16, "" },
        { OpcodeV16.IADD_S16, "s" },
        { OpcodeV16.IMUL_S16, "s" },
        { OpcodeV16.IOFFSET_S16, "s" },
        { OpcodeV16.IOFFSET_S16_LOAD, "s" },
        { OpcodeV16.IOFFSET_S16_STORE, "s" },
        { OpcodeV16.ARRAY_U16, "h" },
        { OpcodeV16.ARRAY_U16_LOAD, "h" },
        { OpcodeV16.ARRAY_U16_STORE, "h" },
        { OpcodeV16.LOCAL_U16, "h" },
        { OpcodeV16.LOCAL_U16_LOAD, "h" },
        { OpcodeV16.LOCAL_U16_STORE, "h" },
        { OpcodeV16.STATIC_U16, "h" },
        { OpcodeV16.STATIC_U16_LOAD, "h" },
        { OpcodeV16.STATIC_U16_STORE, "h" },
        { OpcodeV16.GLOBAL_U16, "h" },
        { OpcodeV16.GLOBAL_U16_LOAD, "h" },
        { OpcodeV16.GLOBAL_U16_STORE, "h" },
        { OpcodeV16.J, "R" },
        { OpcodeV16.JZ, "R" },
        { OpcodeV16.IEQ_JZ, "R" },
        { OpcodeV16.INE_JZ, "R" },
        { OpcodeV16.IGT_JZ, "R" },
        { OpcodeV16.IGE_JZ, "R" },
        { OpcodeV16.ILT_JZ, "R" },
        { OpcodeV16.ILE_JZ, "R" },
        { OpcodeV16.CALL, "a" },
        { OpcodeV16.GLOBAL_U24, "a" },
        { OpcodeV16.GLOBAL_U24_LOAD, "a" },
        { OpcodeV16.GLOBAL_U24_STORE, "a" },
        { OpcodeV16.PUSH_CONST_U24, "a" },
        { OpcodeV16.SWITCH, "" },
        { OpcodeV16.STRING, "" },
        { OpcodeV16.STRINGHASH, "" },
        { OpcodeV16.TEXT_LABEL_ASSIGN_STRING, "b" },
        { OpcodeV16.TEXT_LABEL_ASSIGN_INT, "b" },
        { OpcodeV16.TEXT_LABEL_APPEND_STRING, "b" },
        { OpcodeV16.TEXT_LABEL_APPEND_INT, "b" },
        { OpcodeV16.TEXT_LABEL_COPY, "" },
        { OpcodeV16.CATCH, "" },
        { OpcodeV16.THROW, "" },
        { OpcodeV16.CALLINDIRECT, "" },
        { OpcodeV16.PUSH_CONST_M1, "" },
        { OpcodeV16.PUSH_CONST_0, "" },
        { OpcodeV16.PUSH_CONST_1, "" },
        { OpcodeV16.PUSH_CONST_2, "" },
        { OpcodeV16.PUSH_CONST_3, "" },
        { OpcodeV16.PUSH_CONST_4, "" },
        { OpcodeV16.PUSH_CONST_5, "" },
        { OpcodeV16.PUSH_CONST_6, "" },
        { OpcodeV16.PUSH_CONST_7, "" },
        { OpcodeV16.PUSH_CONST_FM1, "" },
        { OpcodeV16.PUSH_CONST_F0, "" },
        { OpcodeV16.PUSH_CONST_F1, "" },
        { OpcodeV16.PUSH_CONST_F2, "" },
        { OpcodeV16.PUSH_CONST_F3, "" },
        { OpcodeV16.PUSH_CONST_F4, "" },
        { OpcodeV16.PUSH_CONST_F5, "" },
        { OpcodeV16.PUSH_CONST_F6, "" },
        { OpcodeV16.PUSH_CONST_F7, "" },
        { OpcodeV16.LOCAL_LOAD_S, "" },
        { OpcodeV16.LOCAL_STORE_S, "" },
        { OpcodeV16.LOCAL_STORE_SR, "" },
        { OpcodeV16.STATIC_LOAD_S, "" },
        { OpcodeV16.STATIC_STORE_S, "" },
        { OpcodeV16.STATIC_STORE_SR, "" },
        { OpcodeV16.LOAD_N_S, "" },
        { OpcodeV16.STORE_N_S, "" },
        { OpcodeV16.STORE_N_SR, "" },
        { OpcodeV16.GLOBAL_LOAD_S, "" },
        { OpcodeV16.GLOBAL_STORE_S, "" },
        { OpcodeV16.GLOBAL_STORE_SR, "" },
        { OpcodeV16.STATIC_U24, "" },
        { OpcodeV16.STATIC_U24_LOAD, "" },
        { OpcodeV16.STATIC_U24_STORE, "" }
    };

}
